upstream request_service {
    server request-service:8000;
}

upstream notification_service {
    server notification-service:8001;
}

server {
    listen 80;

    location /api/deals {
        proxy_pass http://request_service;
    }

    location /health {
        return 200 "OK\n";
    }
}
